#!/bin/sh
#testcommand - written by Pat OKeefe
# for use by csce215 students.
if [ $# -eq 1 ]; then
   # your script command goes here
   echo your command is $1
else
   echo "usage: `basename $0` [studentid]"
   exit 1
fi
